name       : python-deprecation
version    : 2.0.7
release    : 2
source     :
    - https://files.pythonhosted.org/packages/cd/94/8d9d6303f5ddcbf40959fc2b287479bd9a201ea9483373d9b0882ae7c3ad/deprecation-2.0.7.tar.gz : c0392f676a6146f0238db5744d73e786a43510d54033f80994ef2f4c9df192ed
license    : Apache-2.0
component  : programming.python
summary    : Python library to handle automated deprecations.
description: |
    Python library to handle automated deprecations.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
